name: build

on: [push, pull_request]

env:
  UNITTESTING_TAG: master

jobs:
  linux:
    runs-on: ubuntu-latest
    container: sublimetext/unittesting
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.5'

      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.483'

      - run: clojure -Sdeps '{:deps {nrepl {:mvn/version "0.8.0-SNAPSHOT"}}}' -m nrepl.cmdline --port 1234 &

      - uses: jakejarvis/wait-action@master
        with:
          time: 15s

      - run: sh -e /etc/init.d/xvfb start
      - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.sh
      - run: |
          PATH="$HOME/.local/bin:$PATH"
          sh github.sh bootstrap
          sh github.sh install_package_control
          sh github.sh run_tests

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.5'

      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.483'

      - run: clojure -Sdeps '{:deps {nrepl {:mvn/version "0.8.0-SNAPSHOT"}}}' -m nrepl.cmdline --port 1234 &

      - uses: jakejarvis/wait-action@master
        with:
          time: 15s

      - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.sh
      - run: |
          export PATH="$HOME/.local/bin:$PATH"
          sh github.sh bootstrap
          sh github.sh install_package_control
          sh github.sh run_tests

  # windows:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - run: (new-object net.webclient).DownloadFile("https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.ps1","github.ps1")
  #     - run: |
  #         ./github.ps1 "bootstrap" -verbose
  #         ./github.ps1 "install_package_control" -verbose
  #         ./github.ps1 "run_tests" -verbose
