name: build

on: [push, pull_request]

env:
  UNITTESTING_TAG: master

jobs:
  linux:
    runs-on: ubuntu-latest
    container: sublimetext/unittesting
    services:
      nrepl:
        image: flowthing/nrepl
    steps:
      - uses: actions/checkout@v1
      - run: sh -e /etc/init.d/xvfb start
      - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.sh
      - run: |
          PATH="$HOME/.local/bin:$PATH"
          NREPL_HOST="nrepl"
          sh github.sh bootstrap
          sh github.sh install_package_control
          sh github.sh run_tests
        env:
          NREPL_HOST: nrepl
